### ISSUE TITLE
Image cannot connect to DB

### ISSUE THREAD

**Issue by jhalborg** [develomark/prisma-now#3]
Hey! 

Thanks for a great guide, Zeit Now is awesome! I've pretty much copy+pasted your setup, but I'm having an issue. Note that I'm using AWS Aurora DB instead of Google Cloud. 

It seems the image cannot connect to the DB. I get an output like this:

```
> Successfully built 086ddb645f20
> Successfully tagged registry.now.systems/now/8c565a120ef9e162cfb024f678f1e2411044ae28:latest
> ▲ Storing image
> Build completed
> Verifying instantiation in bru1
> [0]   at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
> [0] Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5000ms.
> [0]   at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
> [0]   at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
> [0]   at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
> [0]   at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
> [0]   at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
> [0] Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
```

I triple-checked the credentials and host, and I'm able to connect to the DB just fine using MySQL Workbench with the same credentials. 

The only tings I changed were: 
* Added `scale` and `alias` keys and values in `now.json`,
* Changed `name` in `now.json`,
* Changed `user` in `config.yml` to the correct value 
* Changed Prisma version in `Dockerfile` to `FROM prismagraphql/prisma:1.13.7`

I'm not that experienced with Docker, but as far as I can tell none of this should change anything. And seeing as I can connect through MySQL Workbench with the credentials, they should be fine too, and the DB should be available to outside connections. 

I'm hoping that you might have an idea that I'm missing? :)

**Comment by jhalborg** [comment]
Found the solution, discussed [here](https://www.prisma.io/forum/t/unable-to-connect-to-aurora-db-through-zeit-now-hosted-docker-prisma-server/4134)
