### ISSUE TITLE
Deploy fails with error "Unable to load Prisma config"

### ISSUE THREAD

**Issue by obibring** [develomark/prisma-now#6]
I followed the instructions listed here and got the following error:
```sh
> ▲ Storing image
> Build completed
> Verifying instantiation in bru1
> [0] Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Expected host to be non-empty
> [0] 	at scala.sys.package$.error(package.scala:27)
> [0] 	at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:40)
> [0] 	at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:40)
> [0] 	at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:15)
> [0] 	at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:12)
> [0] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
> [0] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
> [0] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
> [0] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
> [0] 	at scala.collection.immutable.List.foreach(List.scala:389)
> [0] 	at scala.App.main(App.scala:76)
> [0] 	at scala.App.main$(App.scala:74)
> [0] 	at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:12)
> [0] 	at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala)
> [0] Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Expected host to be non-empty
> [0] 	at scala.sys.package$.error(package.scala:27)
> [0] 	at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:40)
> [0] 	at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:40)
> [0] 	at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:15)
> [0] 	at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:12)
> [0] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
> [0] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
> [0] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
> [0] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
> [0] 	at scala.collection.immutable.List.foreach(List.scala:389)
> [0] 	at scala.App.main(App.scala:76)
> [0] 	at scala.App.main$(App.scala:74)
> [0] 	at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:12)
> [0] 	at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala)
```

I noticed `Dockerfile` contains a build time argument `PRISMA_CONFIG_PATH`, but there are no instructions as to what value should be passed in for this build arg, and hence I am not passing one in. Is this the root of the issue?

**Comment by develomark** [comment]
`PRISMA_CONFIG_PATH` is a runtime variable for Prisma itself.

As for your issue do you have a git you can share? It is hard to diagnose the problem without seeing the source.

My best guess is that the config.yml isn't being deployed to Now or that the secrets have not been set.
